language: java
jdk: oraclejdk12

services:
    - mysql

before_install:
  - mysql -e "SELECT plugin from mysql.user where User='root';"
  - mysql -e "UPDATE mysql.user SET plugin = 'mysql_native_password', authentication_string = PASSWORD('root') WHERE User = 'root';"
  - mysql -e 'FLUSH PRIVILEGES;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS restapi;'

cache:
  directories:
  - $HOME/.m2

  notifications:
    email:
      recipients:
        - andranik.stav@mail.ru
      on_success: never # default: change
      on_failure: always # default: always