language: java
jdk: oraclejdk12

services:
    - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS restapi;'

cache:
  directories:
  - $HOME/.m2

  notifications:
    email:
      recipients:
        - andranik.stav@mail.ru
      on_success: never # default: change
      on_failure: always # default: always