language: java
jdk: oraclejdk12

services:
    - mysql

before_install:
  - sudo mysqladmin -u root password root
#  - mysql -u root -p root
  - mysql -p root -e 'CREATE DATABASE IF NOT EXISTS restapi;'
  - root

cache:
  directories:
  - $HOME/.m2

  notifications:
    email:
      recipients:
        - andranik.stav@mail.ru
      on_success: never # default: change
      on_failure: always # default: always