language: java
jdk: oraclejdk12

services:
    - mysql

before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade
- sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS restapi;'

cache:
  directories:
  - $HOME/.m2

  notifications:
    email:
      recipients:
        - andranik.stav@mail.ru
      on_success: never # default: change
      on_failure: always # default: always